/**
 * Smart TODO Extractor OpenCode Plugin
 *
 * Automatically scans edited/created files for TODO comments with priority detection.
 *
 * **Migration from**: Claude Code todo-extractor.py (PostToolUse)
 *
 * **What it detects**:
 * - TODO, FIXME, HACK, XXX, NOTE, BUG comments
 * - Priority tags: (critical), (high), (P1), (medium), (P2), etc.
 * - Context from surrounding lines
 *
 * **Priority levels**:
 * - Priority 1 (🔴 Critical): TODO(critical), FIXME(high), TODO(P1)
 * - Priority 2 (🟠 High): TODO(high)
 * - Priority 3 (🟡 Medium): TODO(medium), TODO(P2)
 * - Priority 5 (⚪ Normal): Regular TODO/FIXME
 *
 * **Output**: Appends to `TODOS_AUTOGENERATED.md` in project root
 *
 * **Example TODOs detected**:
 * ```
 * // TODO(critical): Fix memory leak in auth
 * // FIXME(high): Refactor database connection pool
 * // TODO: Add input validation
 * ```
 *
 * **Note**: Keeps your manual `TODOS.md` separate - this is auto-generated!
 *
 * **Test this plugin**:
 * 1. Enable plugin in opencode.json
 * 2. Edit a file and add a TODO comment
 * 3. Check TODOS_AUTOGENERATED.md in project root
 * 4. Verify TODO was extracted with correct priority
 */

import { Plugin } from '@opencode/plugin-api'
import * as fs from 'fs/promises'
import * as path from 'path'

interface TodoItem {
  file: string
  line: number
  priority: number
  text: string
  contextBefore: string
  contextAfter: string
}

// Priority labels
const PRIORITY_LABELS: Record<number, string> = {
  1: '🔴 Critical Priority',
  2: '🟠 High Priority',
  3: '🟡 Medium Priority',
  4: '🟢 Low Priority',
  5: '⚪ Normal Priority'
}

export const TodoExtractorPlugin: Plugin = async () => {
  /**
   * Extract TODOs from a file with context and priority
   */
  async function extractTodosFromFile(filePath: string): Promise<TodoItem[]> {
    const todos: TodoItem[] = []

    try {
      const content = await fs.readFile(filePath, 'utf-8')
      const lines = content.split('\n')

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i]
        const lineNum = i + 1

        // Check for TODO patterns
        const todoMatch = line.match(/TODO|FIXME|HACK|XXX|BUG|NOTE/i)

        if (todoMatch) {
          // Determine priority from tags
          let priority = 5 // Default

          if (/(critical)/i.test(line)) {
            priority = 1
          } else if (/(high|P1)/i.test(line)) {
            priority = 1
          } else if (/(medium|P2)/i.test(line)) {
            priority = 3
          } else if (/(low|P3)/i.test(line)) {
            priority = 4
          }

          // Get context
          const contextBefore = i > 0 ? lines[i - 1].trim() : ''
          const contextAfter = i < lines.length - 1 ? lines[i + 1].trim() : ''

          todos.push({
            file: filePath,
            line: lineNum,
            priority,
            text: line.trim(),
            contextBefore,
            contextAfter
          })
        }
      }
    } catch (error) {
      console.warn(`[todo-extractor] Could not read ${filePath}:`, error.message)
    }

    return todos
  }

  /**
   * Get existing TODO identifiers to avoid duplicates
   */
  async function getExistingTodos(outputFile: string): Promise<Set<string>> {
    const existing = new Set<string>()

    try {
      const content = await fs.readFile(outputFile, 'utf-8')
      const matches = content.matchAll(/####\s+(.+?):(\d+)/g)

      for (const match of matches) {
        existing.add(`${match[1]}:${match[2]}`)
      }
    } catch {
      // File doesn't exist yet
    }

    return existing
  }

  return {
    tool: {
      execute: {
        /**
         * Extract TODOs after Edit/Write operations
         */
        after: async (input, output) => {
          // Only process Edit and Write tools
          if (input.tool !== 'Edit' && input.tool !== 'Write') {
            return
          }

          const filePath = input.parameters?.file_path

          if (!filePath) {
            return
          }

          try {
            // Extract TODOs from the file
            const todos = await extractTodosFromFile(filePath)

            if (todos.length === 0) {
              return
            }

            // Output file in project directory
            const projectDir = process.cwd()
            const outputFile = path.join(projectDir, 'TODOS_AUTOGENERATED.md')

            // Get existing TODOs to avoid duplicates
            const existingTodos = await getExistingTodos(outputFile)

            // Filter out duplicates
            const newTodos = todos.filter(todo => {
              const identifier = `${todo.file}:${todo.line}`
              return !existingTodos.has(identifier)
            })

            if (newTodos.length === 0) {
              return
            }

            // Create file header if it doesn't exist
            try {
              await fs.access(outputFile)
            } catch {
              // File doesn't exist, create with header
              const header = `# Auto-Generated TODOs

> This file is automatically generated by the TODO extractor plugin.
> Do NOT edit manually - use TODOS.md for manual tracking.
> Last updated: ${new Date().toISOString().split('T')[0]}

`
              await fs.writeFile(outputFile, header)
            }

            // Group new TODOs by priority
            const todosByPriority: Record<number, TodoItem[]> = {}
            for (const todo of newTodos) {
              if (!todosByPriority[todo.priority]) {
                todosByPriority[todo.priority] = []
              }
              todosByPriority[todo.priority].push(todo)
            }

            // Append new TODOs
            let appendContent = `\n\n## Added: ${new Date().toISOString().split('T').join(' ').split('.')[0]}\n\n`

            // Sort by priority
            const priorities = Object.keys(todosByPriority).map(Number).sort()

            for (const priority of priorities) {
              const todosList = todosByPriority[priority]
              appendContent += `### ${PRIORITY_LABELS[priority] || `Priority ${priority}`}\n\n`

              for (const todo of todosList) {
                appendContent += `#### ${todo.file}:${todo.line}\n`
                appendContent += `- **TODO**: ${todo.text}\n`
                if (todo.contextBefore) {
                  appendContent += `- Context: ${todo.contextBefore}\n`
                }
                appendContent += `- Added: ${new Date().toISOString().split('T').join(' ').split('.')[0]}\n\n`
              }
            }

            await fs.appendFile(outputFile, appendContent)

            console.log(`[todo-extractor] ✓ Extracted ${newTodos.length} TODOs to ${outputFile}`)
          } catch (error) {
            console.warn('[todo-extractor] Error extracting TODOs:', error.message)
          }
        }
      }
    }
  }
}

export default TodoExtractorPlugin
